//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFinal.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLShopQAEntities : DbContext
    {
        public QLShopQAEntities()
            : base("name=QLShopQAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APP_ROLE> APP_ROLE { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERS { get; set; }
        public virtual DbSet<MENU_PRODUCT> MENU_PRODUCT { get; set; }
        public virtual DbSet<ORDER_DETAIL> ORDER_DETAIL { get; set; }
        public virtual DbSet<ORDER> ORDERS { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTs { get; set; }
        public virtual DbSet<PROMOTION> PROMOTIONs { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
        public virtual DbSet<STATUS_ORDER> STATUS_ORDER { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<ORDER_LIST> ORDER_LIST { get; set; }
    
        public virtual ObjectResult<Nullable<int>> SP_DonDaGiao()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_DonDaGiao");
        }
    
        public virtual ObjectResult<SP_ThongKe_SL_Result> SP_ThongKe_SL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ThongKe_SL_Result>("SP_ThongKe_SL");
        }
    
        public virtual ObjectResult<TK_SPTHEO_CATEGORY_Result> TK_SPTHEO_CATEGORY()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TK_SPTHEO_CATEGORY_Result>("TK_SPTHEO_CATEGORY");
        }
    
        public virtual ObjectResult<TK_SPTHEO_CATEGORY1_Result> TK_SPTHEO_CATEGORY1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TK_SPTHEO_CATEGORY1_Result>("TK_SPTHEO_CATEGORY1");
        }
    
        public virtual ObjectResult<sp_report_info_customer_Result> sp_report_info_customer(Nullable<int> id_order)
        {
            var id_orderParameter = id_order.HasValue ?
                new ObjectParameter("id_order", id_order) :
                new ObjectParameter("id_order", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_report_info_customer_Result>("sp_report_info_customer", id_orderParameter);
        }
    
        public virtual ObjectResult<sp_report_day_Result> sp_report_day(Nullable<int> day, Nullable<int> month, Nullable<int> year)
        {
            var dayParameter = day.HasValue ?
                new ObjectParameter("day", day) :
                new ObjectParameter("day", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_report_day_Result>("sp_report_day", dayParameter, monthParameter, yearParameter);
        }
    }
}
