//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFinal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_DETAIL
    {
        public int id_order_detail { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public int id_product { get; set; }
        public int id_order { get; set; }
        public int quantity { get; set; }
        public long unit_price { get; set; }
    
        public virtual ORDER ORDER { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
