//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFinal.Model
{
    using ProjectFinal.ViewModel.Base;
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT:BindableBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.ORDER_DETAIL = new HashSet<ORDER_DETAIL>();
        }
    
        public int id_product { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }

        private string _image_product;
        public string image_product { get=> _image_product; set { _image_product = value;OnPropertyChanged(); } }
        public string name { get; set; }
        public long price { get; set; }
        public string size { get; set; }
        public string color { get; set; }
        public int id_promotion { get; set; }
        public int id_menu_product { get; set; }
    
        public virtual MENU_PRODUCT MENU_PRODUCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_DETAIL> ORDER_DETAIL { get; set; }
        public virtual PROMOTION PROMOTION { get; set; }
    }
}
