//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFinal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATUS_ORDER
    {
        public int id_status { get; set; }
        public string name_status { get; set; }
    }
}
